//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 09.11.2021 18:16:17
        /// ähnelt.
        /// </summary>
        internal static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StartupHost = &quot;shard.ryzom.com:40916&quot;;
        ///StartupPage = &quot;/login/r2_login.php&quot;;
        ///LanguageCode = &quot;en&quot;;		// english
        ///Application = { &quot;ryzom_live&quot;, &quot;./client_ryzom_r.exe&quot;, &quot;./&quot; };
        ///Username = &quot;&quot;;
        ///Password = &quot;&quot;;
        ///SelectCharacter = &quot;-1&quot;;
        ///OnlinePlayersLogger = false;
        ///OnlinePlayersAPI = &quot;&quot;;
        ///AutoJoinTeam = false;
        ///ImpulseDebugger = false;
        ///Debug = false;
        ///UseDatabase = false;
        ///DiscordWebhook = &quot;&quot;;
        ///DecodeVisualProperties = false;
        ///SendPosition = false;
        ///FollowerEnabled = false;
        ///SendPosition = false;
        ///AutoRelogEna [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;database_description&gt;
        ///  &lt;!-- Define bank superclass --&gt;
        ///  &lt;bank_superclass&gt;
        ///    &lt;bank name=&quot;PLR&quot;
        ///          class=&quot;CCDBSynchronised&quot; /&gt;
        ///    &lt;bank name=&quot;GUILD&quot;
        ///          class=&quot;CCDBGroup&quot;
        ///          dbAccessor=&quot;.Database&quot;&gt;
        ///      &lt;include file=&quot;game_share/far_position.h&quot; /&gt;
        ///      &lt;verbatime&gt;inline void _setProp(CCDBSynchronised &amp;amp;db,
        ///      ICDBStructNode *node, TCharConnectionState value, bool
        ///      forceSending = false) { db.x_setProp(node, uint64(value),
        ///      forceSending); } inline void _get [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;client_messages_description&gt;
        ///  &lt;branch name=&quot;TARGET&quot;&gt;
        ///    &lt;leaf name=&quot;PARTY&quot; /&gt;
        ///    &lt;leaf name=&quot;INVENTORY&quot; /&gt;
        ///    &lt;leaf name=&quot;FOLLOW&quot;
        ///          sendto=&quot;AIS&quot;
        ///          format=&quot;&quot;
        ///          description=&quot;The client follows its target&quot; /&gt;
        ///    &lt;leaf name=&quot;NO_FOLLOW&quot;
        ///          sendto=&quot;AIS&quot;
        ///          format=&quot;&quot;
        ///          description=&quot;The client stop following its target&quot; /&gt;
        ///  &lt;/branch&gt;
        ///  &lt;branch name=&quot;CONNECTION&quot;&gt;
        ///    &lt;leaf name=&quot;USER_CHAR&quot; /&gt;
        ///    &lt;leaf name=&quot;NO_USER_CHAR&quot; /&gt;
        ///    &lt;leaf name=&quot;USER_CH [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
    }
}
