//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 28.06.2022 20:31:58
        /// ähnelt.
        /// </summary>
        internal static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StartupHost = &quot;shard.ryzom.com:40916&quot;;
        ///StartupPage = &quot;/login/r2_login.php&quot;;
        ///LanguageCode = &quot;en&quot;;		// english
        ///Application = { &quot;ryzom_live&quot;, &quot;./client_ryzom_r.exe&quot;, &quot;./&quot; };
        ///Username = &quot;&quot;;
        ///Password = &quot;&quot;;
        ///SelectCharacter = &quot;-1&quot;;
        ///Debug = false;
        ///UseDatabase = false;
        ///DiscordWebhook = &quot;&quot;;
        ///DecodeVisualProperties = false;
        ///SendPosition = false;
        /// ähnelt.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;database_description&gt;
        ///  &lt;!-- Define bank superclass --&gt;
        ///  &lt;bank_superclass&gt;
        ///    &lt;bank name=&quot;PLR&quot;
        ///          class=&quot;CCDBSynchronised&quot; /&gt;
        ///    &lt;bank name=&quot;GUILD&quot;
        ///          class=&quot;CCDBGroup&quot;
        ///          dbAccessor=&quot;.Database&quot;&gt;
        ///      &lt;include file=&quot;game_share/far_position.h&quot; /&gt;
        ///      &lt;verbatime&gt;inline void _setProp(CCDBSynchronised &amp;amp;db,
        ///      ICDBStructNode *node, TCharConnectionState value, bool
        ///      forceSending = false) { db.x_setProp(node, uint64(value),
        ///      forceSending); } inline void _getProp(const C [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;database_description&gt;
        ///  &lt;!-- Used because the skill points are locally updated (at buy phrase time)     --&gt;
        ///  &lt;branch name=&quot;USER&quot;
        ///          bank=&quot;PLR&quot;&gt;
        ///    &lt;branch name=&quot;SKILL_POINTS_&quot;
        ///            bank=&quot;PLR&quot;
        ///            count=&quot;4&quot;&gt;
        ///      &lt;leaf name=&quot;VALUE&quot;
        ///            type=&quot;I32&quot; /&gt;
        ///    &lt;/branch&gt;
        ///    &lt;branch name=&quot;FACTION_POINTS_&quot;
        ///            count=&quot;6&quot;&gt;
        ///      &lt;!-- game_share/pvp_clan.h (0 is BeginClans and size is EndClans-BeginClans+1 --&gt;
        ///      &lt;leaf name=&quot;VALUE&quot;
        ///            type=&quot;I32&quot; /&gt;
        ///    [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string local_database {
            get {
                return ResourceManager.GetString("local_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;client_messages_description&gt;
        ///  &lt;branch name=&quot;TARGET&quot;&gt;
        ///    &lt;leaf name=&quot;PARTY&quot; /&gt;
        ///    &lt;leaf name=&quot;INVENTORY&quot; /&gt;
        ///    &lt;leaf name=&quot;FOLLOW&quot;
        ///          sendto=&quot;AIS&quot;
        ///          format=&quot;&quot;
        ///          description=&quot;The client follows its target&quot; /&gt;
        ///    &lt;leaf name=&quot;NO_FOLLOW&quot;
        ///          sendto=&quot;AIS&quot;
        ///          format=&quot;&quot;
        ///          description=&quot;The client stop following its target&quot; /&gt;
        ///  &lt;/branch&gt;
        ///  &lt;branch name=&quot;CONNECTION&quot;&gt;
        ///    &lt;leaf name=&quot;USER_CHAR&quot; /&gt;
        ///    &lt;leaf name=&quot;NO_USER_CHAR&quot; /&gt;
        ///    &lt;leaf name=&quot;USER_CHARS&quot;
        ///          d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5.189.179.173:7497
        ///46.101.96.238:7497
        ///46.101.230.20:7497
        ///46.101.232.224:7497
        ///79.143.187.168:7497
        ///81.169.137.131:7497
        ///81.169.220.180:7497
        ///85.214.131.150:7497
        ///139.162.166.228:7497
        ///139.162.190.26:7497
        ///139.162.170.166:7497
        ///172.104.135.101:7497
        ///172.104.146.154:7497
        ///188.68.36.53:7497
        ///194.163.144.97:7497
        ///194.163.189.206:7497
        ///194.163.145.106:7497
        ///194.195.240.145:7497
        ///207.154.227.216:7497
        ///209.250.233.164:7497
        ///209.250.238.5:7497 ähnelt.
        /// </summary>
        internal static string proxies {
            get {
                return ResourceManager.GetString("proxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] sheet_id {
            get {
                object obj = ResourceManager.GetObject("sheet_id", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
