//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCC.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartupHost = &quot;shard.ryzom.com:40916&quot;;
        ///StartupPage = &quot;/login/r2_login.php&quot;;
        ///LanguageCode = &quot;en&quot;;		// english
        ///Application = { &quot;ryzom_live&quot;, &quot;./client_ryzom_r.exe&quot;, &quot;./&quot; };
        ///Username = &quot;&quot;;
        ///Password = &quot;&quot;;
        ///SelectCharacter = &quot;0&quot;;
        ///OnlinePlayersLogger = false;
        ///OnlinePlayersAPI = &quot;&quot;;.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;database_description&gt;
        ///  &lt;!-- Define bank superclass --&gt;
        ///  &lt;bank_superclass&gt;
        ///    &lt;bank name=&quot;PLR&quot;
        ///          class=&quot;CCDBSynchronised&quot; /&gt;
        ///    &lt;bank name=&quot;GUILD&quot;
        ///          class=&quot;CCDBGroup&quot;
        ///          dbAccessor=&quot;.Database&quot;&gt;
        ///      &lt;include file=&quot;game_share/far_position.h&quot; /&gt;
        ///      &lt;verbatime&gt;inline void _setProp(CCDBSynchronised &amp;amp;db,
        ///      ICDBStructNode *node, TCharConnectionState value, bool
        ///      forceSending = false) { db.x_setProp(node, uint64(value),
        ///      forceSending); } inline void _getProp(const C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;client_messages_description&gt;
        ///  &lt;branch name=&quot;TARGET&quot;&gt;
        ///    &lt;leaf name=&quot;PARTY&quot; /&gt;
        ///    &lt;leaf name=&quot;INVENTORY&quot; /&gt;
        ///    &lt;leaf name=&quot;FOLLOW&quot;
        ///          sendto=&quot;AIS&quot;
        ///          format=&quot;&quot;
        ///          description=&quot;The client follows its target&quot; /&gt;
        ///    &lt;leaf name=&quot;NO_FOLLOW&quot;
        ///          sendto=&quot;AIS&quot;
        ///          format=&quot;&quot;
        ///          description=&quot;The client stop following its target&quot; /&gt;
        ///  &lt;/branch&gt;
        ///  &lt;branch name=&quot;CONNECTION&quot;&gt;
        ///    &lt;leaf name=&quot;USER_CHAR&quot; /&gt;
        ///    &lt;leaf name=&quot;NO_USER_CHAR&quot; /&gt;
        ///    &lt;leaf name=&quot;USER_CHARS&quot;
        ///          d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
    }
}
