name: nightly-release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Create builddate file
        run: echo %date% %time:~0,-3%>"Client\Resources\BuildDate.txt"
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          
      - name: Install dependencies
        run: dotnet restore

      - name: Compile package
        run: dotnet publish Client\Client.csproj -r win-x64 -c Release -p:PublishSingleFile=true -p:UseAppHost=true --self-contained true -p:SolutionDir=".."

      - name: Zip package
        uses: papeloto/action-zip@v1
        with:
          files: bin/Publish/netcoreapp3.1/*.exe
          dest: win-x64.zip

      - name: Upload
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "nightly-release"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            bin/Publish/netcoreapp3.1/*.exe
            win-x64.zip
