name: nightly-release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Create builddate file
        run: echo %date% %time:~0,-3%>"Client\Resources\BuildDate.txt"
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          
      - name: Install dependencies
        run: dotnet restore

      - name: Compile package Win-x64
        run: dotnet publish Client\Client.csproj -r win-x64 -c Release -p:PublishSingleFile=true -p:UseAppHost=true --self-contained true -p:SolutionDir=".." -o="./publish/win64/"

      - name: Zip package Win-x64
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: 'publish/win64/'
          exclusions: '*.pdb'
          filename: 'win-x64.zip'

      - name: Compile package Linux-x64
        run: dotnet publish Client\Client.csproj -r linux-x64 -c Release -p:PublishSingleFile=true -p:UseAppHost=true --self-contained true -p:SolutionDir=".." -o="./publish/linux64/"

      - name: Zip package Linux-x64
        uses: thedoctor0/zip-release@main
        with:
          type: 'tar'
          path: 'publish/linux64/'
          exclusions: '*.pdb'
          filename: 'linux-x64.tar.gz'
          
      - name: Upload
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "nightly-release"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            win-x64.zip
            linux-x64.tar.gz
